-- ENUM TYPES
create type project_goal as enum (
  'visibility',
  'validation',
  'collaboration'
);

create type vote_value as enum (
  'up',
  'down'
);


-- CAMPUSES
create table public.campuses (
  id bigint generated by default as identity primary key,
  name text not null unique
);


-- PROFILES
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,

  name text not null,

  campus_id bigint not null references public.campuses(id),

  tech_stack text[] not null default '{}',

  contact_info text,

  created_at timestamptz not null default now()
);


-- PROJECTS
create table public.projects (
  id bigint generated by default as identity primary key,

  owner_id uuid not null references public.profiles(id) on delete cascade,

  campus_id bigint not null references public.campuses(id),

  title text not null,

  description text not null,

  goal project_goal not null,

  roles_needed text[] not null default '{}',

  images text[] not null,

  created_at timestamptz not null default now(),

  constraint projects_images_minimum
    check (cardinality(images) >= 3),

  constraint projects_roles_only_for_collaboration
    check (
      goal = 'collaboration'
      or cardinality(roles_needed) = 0
    )
);


-- VOTES
create table public.votes (
  id bigint generated by default as identity primary key,

  project_id bigint not null references public.projects(id) on delete cascade,

  user_id uuid not null references public.profiles(id) on delete cascade,

  value vote_value not null,

  created_at timestamptz not null default now(),

  constraint votes_project_user_unique
    unique (project_id, user_id)
);


-- COMMENTS
create table public.comments (
  id bigint generated by default as identity primary key,

  project_id bigint not null references public.projects(id) on delete cascade,

  author_id uuid not null references public.profiles(id) on delete cascade,

  parent_comment_id bigint references public.comments(id) on delete cascade,

  body text not null,

  created_at timestamptz not null default now()
);

-- Row Level Security (RLS)
alter table public.campuses enable row level security;
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.votes enable row level security;
alter table public.comments enable row level security;

create policy "Anyone can view campuses"
on public.campuses
for select
using (true);

create policy "Anyone can view profiles"
on public.profiles
for select
using (true);

create policy "Anyone can view projects"
on public.projects
for select
using (true);

create policy "Users can create their own projects"
on public.projects
for insert
to authenticated
with check (
  owner_id = (select auth.uid())
);

create policy "Users can update their own projects"
on public.projects
for update
to authenticated
using (
  owner_id = (select auth.uid())
)
with check (
  owner_id = (select auth.uid())
);

create policy "Users can delete their own projects"
on public.projects
for delete
to authenticated
using (
  owner_id = (select auth.uid())
);

create policy "Anyone can view votes"
on public.votes
for select
using (true);

create policy "Users can create their own votes"
on public.votes
for insert
to authenticated
with check (
  user_id = (select auth.uid())
);

create policy "Users can update their own votes"
on public.votes
for update
to authenticated
using (
  user_id = (select auth.uid())
)
with check (
  user_id = (select auth.uid())
);

create policy "Users can delete their own votes"
on public.votes
for delete
to authenticated
using (
  user_id = (select auth.uid())
);

create policy "Anyone can view comments"
on public.comments
for select
using (true);

create policy "Users can create comments"
on public.comments
for insert
to authenticated
with check (
  author_id = (select auth.uid())
);

create policy "Users can update their own comments"
on public.comments
for update
to authenticated
using (
  author_id = (select auth.uid())
)
with check (
  author_id = (select auth.uid())
);

create policy "Users can delete their own comments"
on public.comments
for delete
to authenticated
using (
  author_id = (select auth.uid())
);

create policy "Anyone can view profiles"
on public.profiles
for select
using (true);

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using (
  id = (select auth.uid())
)
with check (
  id = (select auth.uid())
);
